// <auto-generated />
using MessageBoard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MessageBoard.Migrations
{
    [DbContext(typeof(MessageBoardContext))]
    [Migration("20210610151018_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MessageBoard.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            Author = "Towelly",
                            Subject = "Beach safety",
                            Text = "Don't forget to bring a towel"
                        },
                        new
                        {
                            MessageId = 2,
                            Author = "StrongBad",
                            Subject = "Shut up",
                            Text = "Shut it up, you"
                        },
                        new
                        {
                            MessageId = 3,
                            Author = "Woolly Mammoth",
                            Subject = "Mammoth shaming",
                            Text = "It's not a coat!"
                        },
                        new
                        {
                            MessageId = 4,
                            Author = "Sea Cow",
                            Subject = "Manitee shaming",
                            Text = "I'm a manitee, I have a layer of blubber to keep me warm."
                        },
                        new
                        {
                            MessageId = 5,
                            Author = "StrongBad",
                            Subject = "Christmas carol remix",
                            Text = "Oh Holy Crap!"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
