// <auto-generated />
using System;
using MessageBoard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MessageBoard.Migrations
{
    [DbContext(typeof(MessageBoardContext))]
    partial class MessageBoardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MessageBoard.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Booze")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("EventId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            Booze = true,
                            Category = "Birthday",
                            Date = new DateTime(2021, 6, 9, 10, 30, 0, 0, DateTimeKind.Utc),
                            Name = "My son's 7th bday"
                        },
                        new
                        {
                            EventId = 2,
                            Booze = false,
                            Category = "Ted Talk",
                            Date = new DateTime(2021, 6, 9, 10, 30, 0, 0, DateTimeKind.Utc),
                            Name = "Mushrooms?"
                        },
                        new
                        {
                            EventId = 3,
                            Booze = true,
                            Category = "Concert",
                            Date = new DateTime(2021, 6, 9, 10, 30, 0, 0, DateTimeKind.Utc),
                            Name = "The Grateful Dead"
                        },
                        new
                        {
                            EventId = 4,
                            Booze = true,
                            Category = "Concert",
                            Date = new DateTime(2021, 6, 9, 10, 30, 0, 0, DateTimeKind.Utc),
                            Name = "Generationals"
                        },
                        new
                        {
                            EventId = 5,
                            Booze = true,
                            Category = "A saucey puppet show",
                            Date = new DateTime(2021, 6, 9, 10, 30, 0, 0, DateTimeKind.Utc),
                            Name = "Where's your hand?"
                        },
                        new
                        {
                            EventId = 6,
                            Booze = false,
                            Category = "Book signing",
                            Date = new DateTime(2021, 6, 9, 10, 30, 0, 0, DateTimeKind.Utc),
                            Name = "David Sedaris: Me Talk Pretty One Day"
                        });
                });

            modelBuilder.Entity("MessageBoard.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            Author = "Towelly",
                            Date = new DateTime(2021, 6, 9, 10, 30, 0, 0, DateTimeKind.Utc),
                            Subject = "Beach safety",
                            Text = "Don't forget to bring a towel"
                        },
                        new
                        {
                            MessageId = 2,
                            Author = "StrongBad",
                            Date = new DateTime(2021, 6, 9, 10, 30, 0, 0, DateTimeKind.Utc),
                            Subject = "Shut up",
                            Text = "Shut it up, you"
                        },
                        new
                        {
                            MessageId = 3,
                            Author = "Woolly Mammoth",
                            Date = new DateTime(2021, 6, 9, 10, 30, 0, 0, DateTimeKind.Utc),
                            Subject = "Mammoth shaming",
                            Text = "It's not a coat!"
                        },
                        new
                        {
                            MessageId = 4,
                            Author = "Sea Cow",
                            Date = new DateTime(2021, 6, 9, 10, 30, 0, 0, DateTimeKind.Utc),
                            Subject = "Manitee shaming",
                            Text = "I'm a manitee, I have a layer of blubber to keep me warm."
                        },
                        new
                        {
                            MessageId = 5,
                            Author = "StrongBad",
                            Date = new DateTime(2021, 6, 9, 10, 30, 0, 0, DateTimeKind.Utc),
                            Subject = "Christmas carol remix",
                            Text = "Oh Holy Crap!"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
